# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b531e5832e47a2d6417bad0a88af4c1e4d5ee2231c9e85129d3bd2f6e915db9991ba1ab0aa5dbb5f7b32e7f51f29ba004c10f48b619b8e2a527e54a891cd1bd5

test:
  secret_key_base: 017bfdfeda5bdba644038b19cf49a3eed0f596c1b922ba1bc7646f9ba664b3e9bbe7d49d889bb7b9cbac3ca8d15580337e3d10e77a4d13e1dbd29efa895b0b2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
